language: c

install:
    - sudo apt-get update > /dev/null
    - sudo apt-get install mono-devel > /dev/null

script:
    - xbuild StarkSoftProxy.csproj

notifications:
    irc:
        channels: "irc.oftc.net#smuxi-devel"
        skip_join: true
        template:
            - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
            - "Build details : %{build_url}"
